export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED'